---
title: "GLEAM custom geneset example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GLEAM custom geneset example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
library(GLEAM)
```

## Custom named-list genesets

```{r, eval=requireNamespace("Seurat", quietly = TRUE)}
library(Seurat)
custom_gs <- list(
  IFN_custom = c("STAT1", "IRF1", "ISG15", "IFIT3"),
  CYT_custom = c("NKG7", "PRF1", "GZMB", "GNLY")
)

ifnb_path <- system.file("extdata", "full_examples", "ifnb_seurat.rds", package = "GLEAM")
if (ifnb_path == "") ifnb_path <- file.path("inst", "extdata", "full_examples", "ifnb_seurat.rds")
seu <- readRDS(ifnb_path)
if (ncol(seu) > 5000) seu <- subset(seu, cells = colnames(seu)[1:5000])

expr_ifnb <- tryCatch(
  Seurat::GetAssayData(seu, assay = DefaultAssay(seu), layer = "counts"),
  error = function(e) Seurat::GetAssayData(seu, assay = DefaultAssay(seu), slot = "counts")
)
meta_ifnb <- seu@meta.data
if (!"group" %in% colnames(meta_ifnb)) meta_ifnb$group <- if ("stim" %in% colnames(meta_ifnb)) as.character(meta_ifnb$stim) else ifelse(seq_len(nrow(meta_ifnb)) <= nrow(meta_ifnb)/2, "A", "B")
if (!"celltype" %in% colnames(meta_ifnb)) meta_ifnb$celltype <- if ("seurat_clusters" %in% colnames(meta_ifnb)) paste0("cluster_", meta_ifnb$seurat_clusters) else as.character(Idents(seu))

sc <- score_signature(
  expr = expr_ifnb,
  meta = meta_ifnb,
  geneset = custom_gs,
  geneset_source = "list",
  seurat = FALSE,
  method = "mean",
  min_genes = 2,
  verbose = FALSE
)

plot_dot(sc, by = c("group", "celltype"))
```
