---
title: "GLEAM trajectory mapping and testing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GLEAM trajectory mapping and testing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
library(GLEAM)
data("toy_expr", package = "GLEAM")
sc <- score_signature(
  expr = toy_expr$expr,
  meta = toy_expr$meta,
  geneset = "immune_small",
  geneset_source = "builtin",
  species = "human",
  seurat = FALSE,
  method = "rank",
  min_genes = 3,
  verbose = FALSE
)
```

## Generic trajectory input

```{r}
traj_tbl <- as_trajectory_data(sc, pseudotime = "pseudotime", lineage = "lineage")
head(traj_tbl)
```

## Trajectory differential testing

```{r}
tr <- test_signature_trajectory(sc, pseudotime = "pseudotime", lineage = "lineage", method = "spearman", verbose = FALSE)
head(tr$table)
```

## Trajectory visualizations

```{r}
plot_pseudotime_score(sc, pathway = rownames(sc$score)[1], pseudotime = "pseudotime", lineage = "lineage")
```

## Optional backend object integration

```{r, eval=FALSE}
# Monocle2 (monocle package)
# tr_m2 <- test_signature_trajectory(sc, pseudotime = cds_monocle2, lineage = cds_monocle2, method = "spearman")

# Monocle3
# tr_m3 <- test_signature_trajectory(sc, pseudotime = cds_monocle3, lineage = "lineage", method = "spearman")

# slingshot
# tr_sl <- test_signature_trajectory(sc, pseudotime = sds, lineage = sds, method = "spearman")
```

